language: node_js
node_js:
  - "4.0"
sudo: false
services:
  - mongodb
before_script: npm shrinkwrap
after_script: npm run report-coverage
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: us-west-2
  zip-file: dist/badger.zip
  app: oss-demos
  env: badger
  bucket_name: ats-travis
  bucket_path: badger
  on:
    repo: atsid/badger
    branch: master
    node: '4.0'
