language: node_js
node_js:
  - "node"
  - "6"
deploy:
  - provider: script
    script: NODE_ENV=production npm run publish
    on: 
      branch: release
  - provider: script
    script: NODE_ENV=production npm run publish
    on: 
      branch: master