language: node_js
node_js:
  - "4.0"
sudo: false
before_script: npm shrinkwrap
after_script: npm run report-coverage && npm run archive
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: us-west-2
  zip-file: dist/badger.zip
  app: oss-demos
  env: badger
  bucket_name: ats-badger-artifacts
  on:
    repo: atsid/badger
    branch: master
