language: node_js
node_js:
  - "node"
  - "6"
deploy:
  - provider: script
    script: scripts/deploy/release.sh
    skip_cleanup: true
    on: 
      branch: release
  - provider: script
    script: scripts/deploy/master.sh
    skip_cleanup: true
    on: 
      branch: master