language: node_js
node_js:
  - "node"
  - "6"
deploy:
  - provider: script
    script: GITHUB_CLIENT_ID=$PROD_GH_CLIENT_ID NODE_ENV=production npm run publish
    on: 
      branch: release
  - provider: script
    script: GITHUB_CLIENT_ID=$INTEG_GH_CLIENT_ID NODE_ENV=production npm run publish
    on: 
      branch: master